# services/Dockerfile_ml_service
FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
  && rm -rf /var/lib/apt/lists/*

# зависимости
COPY ml_service/requirements.txt /app/requirements.txt
RUN pip install --upgrade pip && pip install -r /app/requirements.txt

# код сервиса
COPY ml_service /app/services/ml_service

# дефолты (перекроются .env)
ENV MODEL_DIR=/app/models \
    PORT=8765

EXPOSE 8765

CMD ["uvicorn", "services.ml_service.main:app", "--host", "0.0.0.0", "--port", "8765"]